id: ID4968044
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T02:01:01+00:00'
last_modified: '2022-06-07T17:26:50.434150+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9274
  title: སྲོག་བདག་ཨ་བསེ་དང་ཤུགས་ལྡན་གྱི་ལོ་རྒྱུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    E044:
      image_group_id: I1KG9532
      title: ''
      total_pages: 37
      order: 1
      base_file: E044.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
